---
- name: Install custom hosts file
  template:
    src: etc_hosts.j2
    dest: "{{ hosts_file | default('/etc/hosts') }}"
    owner: root
    group: root
    mode: 0644
  when: hosts_entries is defined and hosts_entries|length > 0
